services:
  database:
    container_name: pulse_database
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_secret
      LANG: C.UTF-8
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net
    healthcheck:
      interval: 5s
      test: (mysqladmin ping --silent && exit 1) || echo 0
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  backend:
    container_name: pulse_backend
    env_file: ".env"
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "3000:3000"
      - "5005:5005"
    networks:
      - net
    depends_on:
      database:
        condition: service_healthy
  frontend:
    container_name: pulse_frontend
    env_file: ".env"
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      backend:
        condition: service_started
volumes:
  mysql_data:
networks:
  net: