/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface Channel
 */
export interface Channel {

    /**
     * @type {string}
     * @memberof Channel
     */
    type?: ChannelTypeEnum;

    /**
     * @type {string}
     * @memberof Channel
     */
    name?: string;

    /**
     * @type {User}
     * @memberof Channel
     */
    admin?: User;

    /**
     * @type {number}
     * @memberof Channel
     */
    id?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ChannelTypeEnum {
    Channel = 'Channel',
    PrivateChat = 'PrivateChat',
    GroupChat = 'GroupChat',
    CommentsChat = 'CommentsChat'
}

