/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Channel } from './channel';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface Message
 */
export interface Message {

    /**
     * @type {Date}
     * @memberof Message
     */
    timestamp: Date;

    /**
     * @type {string}
     * @memberof Message
     */
    content: string;

    /**
     * @type {Channel}
     * @memberof Message
     */
    channel: Channel;

    /**
     * @type {User}
     * @memberof Message
     */
    user: User;

    /**
     * @type {number}
     * @memberof Message
     */
    id?: number;
}
